# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_wasserstein_test_rcpp_hello_world`)
}

numericVectorRep <- function(n, e) {
    .Call(`_wasserstein_test_numericVectorRep`, n, e)
}

numericVectorMean <- function(x) {
    .Call(`_wasserstein_test_numericVectorMean`, x)
}

numericVectorAbs <- function(x) {
    .Call(`_wasserstein_test_numericVectorAbs`, x)
}

numericVectorSum <- function(x) {
    .Call(`_wasserstein_test_numericVectorSum`, x)
}

permutate <- function(x, replace = FALSE, prob = as.numeric( c())) {
    .Call(`_wasserstein_test_permutate`, x, replace, prob)
}

permutations <- function(x, num_permutations) {
    .Call(`_wasserstein_test_permutations`, x, num_permutations)
}

wasserstein_metric <- function(a, b, p = 1, wa_ = NULL, wb_ = NULL) {
    .Call(`_wasserstein_test_wasserstein_metric`, a, b, p, wa_, wb_)
}

