# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' vector_factor_multiplication
#'
#' @param x vector 
#' @param factor numerical
#' @return a vector containing the product of each element in x and the factor
#'
NULL

#' vector_vector_multiplication
#'
#' @param x vector 
#' @param y vector
#' @return a vector containing the product of each element
#'   in x and the factor
#'
NULL

#' vector_pow
#'
#' @param x vector 
#' @param exp numerical representing the exponent
#' @return a vector containing a copy of x with each 
#'   element raised to the power of exp
#'
NULL

#' vector_sum
#'
#' @param x vector with numerical elements 
#' @return The sum of all elements in x
#'
NULL

#' vector_vector_subtract
#'
#' @param x vector 
#' @param y vector
#' @return vector representing the subtraction x - y
#'
NULL

#' vector_factor_division
#'
#' @param x vector 
#' @param divisor numerical
#' @return a vector containing the result of each 
#'   element in x divided by divisor
#'
NULL

#' vector_vector_division
#'
#' @param x vector 
#' @param y vector
#' @return a vector containing the product of each element
#'   in x and the factor
#'
NULL

#' vector_mean
#'
#' @param x vector with numericals
#' @return the average of all elements in x
#'
NULL

#' vector_standard_deviation
#'
#' @param x vector with numericals
#' @return the standard deviation of all elements in x
#'
NULL

#' vector_absolute
#'
#' @param x vector with numericals
#' @return vector with the absolute values of all elements in x
#'
NULL

#' vector_vector_correlation
#'
#' @param x vector with numericals
#' @param y vector with numericals
#' @param mean_x optional pre-calculated mean of x
#' @param mean_y optional pre-calculated mean of y
#' @return pearsons correlation of the vectors x and y
#'
NULL

#' vector_cumulative_sum
#' 
#' The cumulative sum x[i] is the sum of all previous elements in x:
#' x[i] = x[i-1] + x[i-2] + ... + x[0]
#'
#' @param x vector of numericals
#' @return a vector containing cumulative sums of the values in x
#'
NULL

#' Repeat weighted
#'
#' Each element x[i] in the given input vector x is repeated according
#' to the weight vector at position i
#'
#' @param x vector with numeric elements
#' @param freq_table vector<int> representing the numer of repeats
#' @return the weight-repeated NumericVector of x
#'
NULL

#' vector_concatenate
#'
#' `concat` returns a vector that represents the concatenation of two input vectors.
#' The elements of the second given vector are appended to a copy of the first vector.
#'
#' @param x vector
#' @param y vector
#' @return concatenation of y after x
#'
NULL

#' interval_table
#'
#' Given a vector datavec and a vector with interval breaks,
#' a histogram with the number of elements in datavec that fall into each
#' of the intervals is returned.
#'
#' @param datavec vector with elements to be distributed over the intervals
#' @param interval_breaks vector with n interval_borders that are
#'		interpreted as interval breaks:\cr 
#'		(-Inf, breaks[0]], (breaks[0], breaks[1]), ... , (breaks(n), Inf)
#' @param ini_value default frequency value
#'
#' @return frequency with which elements of datavec fall into each of the 
#'    intervals defined by interval_breaks
#'
NULL

#' permutations
#'
#' Returns permutations of a given NumericVector as columns in a NumericMatrix
#' object. 
#' @param x :	NumericVector representing a vector that is to be permutated
#' @param num_permutations : 	Int representing the number of permutations
#'							that are to be performed.
#' @return a matrix containing in every column one permutations of the input vector
#'
#' @export
permutations <- function(x, num_permutations) {
    .Call('_diffexpR_permutations', PACKAGE = 'diffexpR', x, num_permutations)
}

#' sq_wasserstein
#'
#' Squared Wasserstein distance between two vectors.
#'
#' The squared wasserstein distance has useful properties for decomposition.
#' @param a Vector representing an empirical distribution under condition A 
#' @param b Vector representing an empirical distribution under condition B
#'	@param p exponent of the wasserstine distance
#' @return The squared wasserstein distance between a and b
#'
#' @export
sq_wasserstein <- function(a_, b_, p = 1) {
    .Call('_diffexpR_sq_wasserstein', PACKAGE = 'diffexpR', a_, b_, p)
}

#' sq_wasserstein_decomp
#'
#' Squared Wasserstein distance between two vectors, decomposed into size, location and shape. 
#'
#' @param a Vector representing an empirical distribution under condition A 
#' @param b Vector representing an empirical distribution under condition B
#'	@param p exponent of the wasserstine distance
#' @return The wasserstein distance between a and b, decomposed into terms for size, location, and shape
#'
#' @export
sq_wasserstein_decomp <- function(a_, b_, p = 1) {
    .Call('_diffexpR_sq_wasserstein_decomp', PACKAGE = 'diffexpR', a_, b_, p)
}

#' wasserstein
#'
#' Wasserstein distance between two vectors. 
#'
#' @param a Vector representing an empirical distribution under condition A 
#' @param b Vector representing an empirical distribution under condition B
#'	@param p exponent of the wasserstine distance
#'
#' @return The wasserstein distance between a and b
#'
#' @export
wasserstein <- function(a_, b_, p = 1) {
    .Call('_diffexpR_wasserstein', PACKAGE = 'diffexpR', a_, b_, p)
}

wasserstein_metric <- function(a_, b_, wa_, wb_, p) {
    .Call('_diffexpR_wasserstein_metric', PACKAGE = 'diffexpR', a_, b_, wa_, wb_, p)
}

multiply_test_export <- function(x_, y_) {
    .Call('_diffexpR_multiply_test_export', PACKAGE = 'diffexpR', x_, y_)
}

multiply_test_export_sv <- function(x_, y_) {
    .Call('_diffexpR_multiply_test_export_sv', PACKAGE = 'diffexpR', x_, y_)
}

pow_test_export <- function(x_, exp) {
    .Call('_diffexpR_pow_test_export', PACKAGE = 'diffexpR', x_, exp)
}

abs_test_export <- function(x_) {
    .Call('_diffexpR_abs_test_export', PACKAGE = 'diffexpR', x_)
}

sum_test_export <- function(x_) {
    .Call('_diffexpR_sum_test_export', PACKAGE = 'diffexpR', x_)
}

subtract_test_export <- function(x_, y_) {
    .Call('_diffexpR_subtract_test_export', PACKAGE = 'diffexpR', x_, y_)
}

divide_test_export_sv <- function(x_, y_) {
    .Call('_diffexpR_divide_test_export_sv', PACKAGE = 'diffexpR', x_, y_)
}

divide_test_export_vectors <- function(x_, y_) {
    .Call('_diffexpR_divide_test_export_vectors', PACKAGE = 'diffexpR', x_, y_)
}

mean_test_export <- function(x_) {
    .Call('_diffexpR_mean_test_export', PACKAGE = 'diffexpR', x_)
}

sd_test_export <- function(x_) {
    .Call('_diffexpR_sd_test_export', PACKAGE = 'diffexpR', x_)
}

cumSum_test_export <- function(x_, last_index = 0L) {
    .Call('_diffexpR_cumSum_test_export', PACKAGE = 'diffexpR', x_, last_index)
}

cor_test_export <- function(x_, y_) {
    .Call('_diffexpR_cor_test_export', PACKAGE = 'diffexpR', x_, y_)
}

emp_equi_quantiles_test_export <- function(x_, K) {
    .Call('_diffexpR_emp_equi_quantiles_test_export', PACKAGE = 'diffexpR', x_, K)
}

rep_weighted_test_export <- function(x_, weights_) {
    .Call('_diffexpR_rep_weighted_test_export', PACKAGE = 'diffexpR', x_, weights_)
}

concat_test_export <- function(x_, y_) {
    .Call('_diffexpR_concat_test_export', PACKAGE = 'diffexpR', x_, y_)
}

interval_table_test_export <- function(data_, breaks_, default_freq = 0L) {
    .Call('_diffexpR_interval_table_test_export', PACKAGE = 'diffexpR', data_, breaks_, default_freq)
}

